[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "hpes_sim"
version = "0.1.0"
dependencies = [
    "numpy",
    "matplotlib",
    "pandas",
    "scipy"
]
description = "A Hydro-Pneumatic Energy Storage Simulation package."
readme = "README.md"
requires-python = ">=3.14"
license = "MIT"
license-files = ["LICENSE"]
authors = [
    {name = "Michael Mercieca", email = "mmercieca07@gmail.com"},
]
keywords = ["hydro", "pneumatic", "energy", "storage", "simulation", "wind"]

[project.urls]
GitHub = "https://github.com/MichaelMercieca/Hydro-Pneumatic-Energy-Storage-HPES-Simulation"

[dependency-groups]
dev = [
    "pytest"
]

[tool.pytest.ini_options]
testpaths = ["tests"]